wandb_version: 1

_content:
  desc: null
  value:
    datamodule: '{''covariates'': [], ''sampler'': {''sampler_type'': ''DummySampler''},
      ''batch_size'': 512, ''partition'': 0, ''num_workers'': 4, ''label_definition'':
      {''all_cause_death'': True, ''phecodes'': True, ''custom'': []}, ''t0_mode'':
      ''recruitment'', ''use_top_n_phecodes'': 1683, ''edge_weight_threshold'': 0.1,
      ''min_edge_type_fraction'': 0.001, ''buffer_years'': 0.0, ''filter_input_origins'':
      [], ''load_embeddings_path'': ''/sc-projects/sc-proj-ukb-cvd/data/2_datasets_pre/220208_graphembeddings/embeddings_leonard/Embedding_dict_NodePiece_t2.feather'',
      ''use_loss_weights'': False, ''task'': ''tte'', ''task_kwargs'': {}}'
    head: '{''model_type'': ''MLP'', ''dropout'': 0.6728016211425569, ''kwargs'':
      {''num_hidden'': 1024, ''num_layers'': 1, ''detach_clf'': False, ''initial_dropout'':
      0.2853273875764176}}'
    model: '{''model_type'': ''GraphEmbeddings'', ''num_hidden'': 256, ''num_outputs'':
      256, ''num_blocks'': 3, ''dropout'': 0.1, ''weight_norm'': True, ''shuffled'':
      False}'
    setup: '{''entity'': ''cardiors'', ''project'': ''RecordGraphs'', ''group'': None,
      ''name'': ''emb_run_thesis_NodePiece_t2'', ''root'': {''charite-hpc'': ''/sc-projects/sc-proj-ukb-cvd'',
      ''eils-hpc'': ''/data/analysis/ag-reils/ag-reils-shared/cardioRS''}, ''data_path'':
      ''data/2_datasets_pre/211110_anewbeginning/artifacts'', ''output_path'': ''results/models'',
      ''use_data_artifact_if_available'': True, ''data'': {''drop_shortcut_edges'':
      True, ''drop_individuals_without_gp'': False, ''min_record_counts'': 100}, ''data_identifier'':
      ''WandBGraphDataNoShortcuts_emb1024_min100_leonard_thesis:v0'', ''tags'': [''leonard_thesis:v0'',
      ''only relation, DeepMLP'', ''-dim 1024'', ''32768'', ''NodePiece'']}'
    trainer: '{''gpus'': [0], ''precision'': 16, ''max_epochs'': 10000, ''num_sanity_val_steps'':
      -1, ''detect_anomaly'': False, ''amp_backend'': ''native'', ''accumulate_grad_batches'':
      1}'
    training: '{''exclusions_on_losses'': False, ''exclusions_on_metrics'': True,
      ''gradient_checkpointing'': False, ''contrastive_loss_factor'': 0, ''endpoint_loss_factor'':
      1, ''vicreg_loss_factor'': 0, ''node_dropout'': None, ''normalize_node_embeddings'':
      True, ''binarize_records'': True, ''write_predictions'': False, ''write_embeddings'':
      False, ''write_attributions'': False, ''attribution_baseline_mode'': ''zeros'',
      ''use_endpoint_embeddings'': False, ''patience'': 5, ''optimizer_kwargs'': {''weight_decay'':
      0.05082949318285612, ''lr'': 0.0002403050945345336}}'
    user_config: /home/tilingl/ehrgraphs/config/experiments/graphembeddings_leonard_thesis_220421.yaml
_flags_cache:
  desc: null
  value:
    struct: true
_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=None, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2022-05-13'', (''%H-%M-%S'',): ''10-36-41''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1652431367
    t:
      1:
      - 1
      - 5
      - 9
      3:
      - 13
      - 15
      - 16
      4: 3.9.7
      5: 0.12.7
      8:
      - 5
